[package]
name = "htop_systeminfo"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "htop_systeminfo"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.27.0"
sysinfo = "0.28.2"
